//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсилио
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Каталог_видеоигрEntities2 : DbContext
    {
        public Каталог_видеоигрEntities2()
            : base("name=Каталог_видеоигрEntities2")
        {
        }
        private static Каталог_видеоигрEntities2 a;
        public static Каталог_видеоигрEntities2 GetContext()
        {
            if (a == null)
            {
                a = new Каталог_видеоигрEntities2();
            }
            return a;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Администраторы> Администраторы { get; set; }
        public virtual DbSet<Видеоигра> Видеоигра { get; set; }
        public virtual DbSet<Избранное> Избранное { get; set; }
        public virtual DbSet<лого> лого { get; set; }
        public virtual DbSet<Оценённые> Оценённые { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
    }
}
