//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсилио
{
    using System;
    using System.Collections.Generic;
    
    public partial class Видеоигра
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Видеоигра()
        {
            this.Избранное = new HashSet<Избранное>();
            this.Оценённые = new HashSet<Оценённые>();
        }
    
        public int Номер { get; set; }
        public string Название { get; set; }
        public string Дата_выхода { get; set; }
        public string Жанр { get; set; }
        public double Рейтинг { get; set; }
        public int Количество_оценок { get; set; }
        public string Студия_разработчик { get; set; }
        public string Издатель { get; set; }
        public string Описание { get; set; }
        public string Среднее_время_прохождения { get; set; }
        public string Минимальные_системные_требования { get; set; }
        public string Рекомендованные_системные_требования { get; set; }
        public Nullable<int> картинка { get; set; }
    
        public virtual лого лого { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Избранное> Избранное { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценённые> Оценённые { get; set; }
    }
}
